### ISSUE TITLE
Remove binaries

### ISSUE THREAD

**Issue by Servostar** [PlexSheep/c-basic#1]
Either remove binaries from main branch or create a release.
Just add the bin folder to `.gitignore` and remove 'em from the repo.
At least consider marking the binaries by their platform (Linux, Windows, x86_64, ...)

**Comment by PlexSheep** [comment]
I removed bin directories and updated the README. See https://github.com/PlexSheep/c-basic/commit/0e95262ce0693ab1e11305c5dbd13a31e4dd6162
